jobs:
  - name: docker-spring-manifest
    type: manifest
    steps:
     - IN: docker-spring-image
     - IN: docker-options

  - name: deploy-pipelines-spring
    type: deploy
    steps:
      - IN: docker-spring-manifest
#      - IN: docker-options
      - IN: docker-cluster
      - TASK: managed
        deployMethod: blueGreen
